[env]
freq_hz = 10
robot_port = 6001
hostname = "127.0.0.1"
joint_ids=[1, 2, 3, 4, 5, 6]
start_joints_deg = [0.0, -90.0, -90.0, -90.0, 90.0, -180.0]
joint_signs = [1.0, 1.0, -1.0, 1.0, 1.0, 1.0]
joint_offsets = [0.0, 3.142, -1.571, 1.571, 3.142, 6.283]
gripper_config=[7, 195, 153]
data_dir = "./data"
bimanual = false
dataset_type="lerobot" # gello, lerobot

[robot]
type = "ur"
hostname = "192.168.0.3"
node_hostname = "127.0.0.1"
node_port = 6001
gripper = "shadowtac" # none, robotiq, shadowtac
gripper_hostname = "/dev/ttyACM0" # Either hostname/ip address/serial port, depending on the gripper comms protocol.
gripper_port = 115200 # Either port number of baud rate
x_limits_m = [-1.0, 1.0]
y_limits_m = [-0.4, 0.6]
z_limits_m = [0.03, 1.5]

[camera_server]
hostname = "127.0.0.1"

[[camera_clients]]
name = "wrist"
port = 5000

[[camera_clients]]
name = "base"
port = 5001

[inference]
policy = "act" # act, diffusion, smolvla
dataset_url = "ur5e_gello_cube_v7"
episode_idx = 0
checkpoint_path = "/home/zico/dev/gello_software/outputs/train/act_ur5e_gello_cube_v5/checkpoints/300000/pretrained_model"
task = "pick red cube and place on yellow card"
